version: "3.1"

services:
  db:
    container_name: blitz-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - blitz-db-data:/var/lib/postgresql/data
    # 5432 is often already taken
    ports:
      - 6543:5432

volumes:
  blitz-db-data:
